### ISSUE TITLE
Example code for using 2 mics simultaneously and streaming it in real time over network while saving the stream locally to a USB flash disc

### ISSUE THREAD

**Issue by dumblob** [ohmic-net/pico_dsp#6]
I wonder if anyone tried what the topic describes?

Any hints how to go about it (especially the "parallel" nature of it with real-time guarantees).

**Comment by andy-wi** [comment]
One possible approach could be; 

1. Modify this code for the 2 microphones, currently it uses one (mono) input - https://github.com/ohmic-net/puca_dsp/tree/main/puca_dsp-platformio-arduino-esp32/original%20edition/arduino-esp32_mono_mic_input you might want one interleaved array for stereo rather than 2 separate arrays for left and right signals. 
2. Write the output to a ringbuffer, then, when the ringbuffer is full read from it to the write buffer for the flash memory, and to the buffer for the network stream. Possibly you could use 2 ringbuffers, the ringbuffer for the network stream may need to be larger size depending on the network latency?
 
I've used this approach for writing to SPIFFS or SD card for real time recording, but not at the same time / in parallel with network streaming. I don't think from a hardware perspective that the USB port on puca_dsp can be configured as a USB flash disc also, you might need to write a UART to USB memory stick drive / bridge using another one of the UART ports on the ESP32.

**Comment by dumblob** [comment]
Thanks for the pointers - sounds kind of doable. Btw. the interleaved array is an interesting idea. Never saw that before :wink:.

Now I will need to think about how to encrypt the network stream to hide the content, how to (re-)authenticate the downloading site (without stream interruption), etc.
